### ISSUE TITLE
`nstd_core_mem_copy` functions cannot actually be called in `const`

### ISSUE THREAD

**Issue by RalfJung** [RustEnthusiast/nstd#23]
The [`nstd_core_mem_copy` function](https://github.com/RustEnthusiast/nstd/blob/fa71891d34ac46785c277ce1fada34bff11f86e1/src/core/mem.rs#L285C21-L285C39) needs a mutable raw pointer (`dest: *mut NSTDByte`). There is currently no way to create such a pointer in `const` on stable. (Well, one can of course cast a shared reference to `*mut`, but then writing to that would be UB.)

The `copy_nonoverlapping` functions inside `nstd_core_mem_copy`  were accidentally made stable on const, but can't actually be used. We are [debating](https://github.com/rust-lang/rust/pull/117905) whether we want to take back stabilization to avoid misuse (which we are already seeing).

Is there any issue with making `nstd_core_mem_copy` (and `nstd_core_mem_copy_overlapping`) not be `const fn` any more?

**Comment by RustEnthusiast** [comment]
@RalfJung thank you for the heads up!
> Is there any issue with making `nstd_core_mem_copy` (and `nstd_core_mem_copy_overlapping`) not be `const fn` any more?

Not at all, I'll update these functions now.

**Comment by RustEnthusiast** [comment]
Fixed in 0263142.
